name: docking
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pdb2pqr
  - meeko
  - openmm
  - pdbfixer
  - pymol-open-source
  - rdkit
  - biopython
  - numpy
  - pip
  - pip:
    - dimorphite-dl
